### ISSUE TITLE
Feature request: Add support for YouTube Music

### ISSUE THREAD

**Issue by qwertpi** [Daniel-CG-Wright/SwiftStats#5]
Google allow you to export your combined YouTube and YouTube Music  "watch" history as JSON from their GDPR dashboard, albeit with a slightly more complicated format and without the time spent "watching". It would be nice if this tool supported this format as well.  
_**This is at least as much a reminder for myself to do this if I ever have the spare time as it is a request for you to do this.**_

Format:
```
{
  "header": "YouTube Music" or "YouTube",
  "title": "Watched <songTitle>",
  "titleUrl": "https://music.youtube.com/watch?v\u003d<videoID>",
  "subtitles": [{
    "name": "<artistName> - Topic" if they have a YouTube Music artist page which is almost always the case,
    "url": "https://www.youtube.com/channel/<artistID>"
  }],
  "time": "<timestamp>",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
}
```

So we would need to:

- Update `validateFileContent` to also accept this format
- Filter down to rows with `'header'` `"YouTube Music"`
- Parse out the track title by discarding the `"Watched "` from `'title'`
- Parse out the artist name by discarding the `"- Topic"` from  `'subtitles'['name']` (if it has this, else skip over the row)
- Parse the timestamp `'time'`
- Although the time spent listening to the song is not accessible, the length of the song itself could presumably be accessed using the video id in `'titleURL'` but this would not be necessary for a MVP
- **This issue raises a broader question of whether there should be a single source of parsed data rather than several instances of `JSON.parse(fileContent);` which would all have to be extended to include some further parsing for this case?**

Sample data:
```
[{
  "header": "YouTube Music",
  "title": "Watched Stick Season",
  "titleUrl": "https://music.youtube.com/watch?v\u003dgLA6VyT4QOw",
  "subtitles": [{
    "name": "Noah Kahan - Topic",
    "url": "https://www.youtube.com/channel/UCwGXlFP4Ba5do7KoxRJYgVQ"
  }],
  "time": "2023-12-24T16:39:41.496Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched the last great american dynasty",
  "titleUrl": "https://music.youtube.com/watch?v\u003dOIlR5mOc9_s",
  "subtitles": [{
    "name": "Taylor Swift - Topic",
    "url": "https://www.youtube.com/channel/UCPC0L1d253x-KuMNwa05TpA"
  }],
  "time": "2023-12-24T16:35:50.361Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched White Christmas",
  "titleUrl": "https://music.youtube.com/watch?v\u003dGmBOuKnLnis",
  "subtitles": [{
    "name": "Taylor Swift - Topic",
    "url": "https://www.youtube.com/channel/UCPC0L1d253x-KuMNwa05TpA"
  }],
  "time": "2023-12-24T16:33:16.296Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched Beautiful People (feat. Khalid)",
  "titleUrl": "https://music.youtube.com/watch?v\u003d6v8BmMirkUk",
  "subtitles": [{
    "name": "Ed Sheeran - Topic",
    "url": "https://www.youtube.com/channel/UClmXPfaYhXOYsNn_QUyheWQ"
  }],
  "time": "2023-12-24T14:35:29.005Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched When Your Heart Stops Beating",
  "titleUrl": "https://music.youtube.com/watch?v\u003dSlmK3eSiySI",
  "subtitles": [{
    "name": "+44 - Topic",
    "url": "https://www.youtube.com/channel/UCp3at6IkqAVAUGunEqEeD4w"
  }],
  "time": "2023-12-24T14:35:16.255Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched The Reynolds Pamphlet",
  "titleUrl": "https://music.youtube.com/watch?v\u003d0h2I8Dlu3_U",
  "subtitles": [{
    "name": "Lin-Manuel Miranda - Topic",
    "url": "https://www.youtube.com/channel/UCAFIersvPYEQzT7XPRWUj8g"
  }],
  "time": "2023-12-24T14:34:18.405Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched The Adams Administration",
  "titleUrl": "https://music.youtube.com/watch?v\u003dPouTf9gYZMw",
  "subtitles": [{
    "name": "Original Broadway Cast of Hamilton - Topic",
    "url": "https://www.youtube.com/channel/UC34heOtZWrXdl5YqhrlMDOQ"
  }],
  "time": "2023-12-24T14:34:04.234Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched Tom Lehrer - Poisoning Pigeons In The Park",
  "titleUrl": "https://music.youtube.com/watch?v\u003dyhuMLpdnOjY",
  "subtitles": [{
    "name": "The Tom Lehrer Wisdom Channel",
    "url": "https://www.youtube.com/channel/UCuvRHuqLf6F3tV3jA2cyhUA"
  }],
  "time": "2023-12-24T14:32:43.344Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched GROWING UP ON THE INTERNET",
  "titleUrl": "https://music.youtube.com/watch?v\u003dy6HvAnAnmuI",
  "subtitles": [{
    "name": "NOAHFINNCE - Topic",
    "url": "https://www.youtube.com/channel/UCMe3q9FG1F6m6rUAM7y2khw"
  }],
  "time": "2023-12-24T14:32:21.510Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube Music",
  "title": "Watched Robots \u0026 Aliens",
  "titleUrl": "https://music.youtube.com/watch?v\u003dLXl9OJXWd8U",
  "subtitles": [{
    "name": "Forever The Sickest Kids - Topic",
    "url": "https://www.youtube.com/channel/UCx7p4GB76Zf14f20RFyBvkg"
  }],
  "time": "2023-12-24T14:32:09.872Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
},{
  "header": "YouTube",
  "title": "Watched Lecture 9.2 Max-flow min-cut theorem via LP duality, Introduction to approximation algorithms",
  "titleUrl": "https://www.youtube.com/watch?v\u003dQS9OMuq8ibc",
  "subtitles": [{
    "name": "Thatchaphol Saranurak",
    "url": "https://www.youtube.com/channel/UCh575jx8hkFTIZaKe1nldwQ"
  }],
  "time": "2023-12-19T12:48:44.612Z",
  "products": ["YouTube"],
  "activityControls": ["YouTube watch history"]
}]
```

**Comment by Daniel-CG-Wright** [comment]
Thanks for the suggestion, i'll have a closer look - i definitely need a centralised source of info rather than multiple parsers, i decided on that halfway through but couldnt be bothered to change it. Might have a stripped down version of the UI without the listening clocks (replacing them with streaming clocks) and without listening time on the UI, if a youtube file is detected.

**Comment by qwertpi** [comment]
Nice!

For completeness, snags I believe I have found while playing around with this that you may or may not wish to open separate issues for:
• Once a file has been uploaded you cannot replace it without clearing browser data for the site, a reset button would be useful
• There is a (admitedly reasonable) assumption made that the most recent stream is the last entry in the json and the oldest stream is the first entry, it seems like it would not be too challenging to find to explicitly find the oldest and newest
• Users must take it on trust that the code running in their browser is the same as the privacy protecting published source code as the code running in the browser is obfuscated
• This repo is open-sourced under creative commons but creative commons is not recommended for source code (https://creativecommons.org/faq/#Can_I_use_a_Creative_Commons_license_for_software), for alternatives you may wish to consult https://choosealicense.com/licenses/

**Comment by Daniel-CG-Wright** [comment]
Thanks for pointing these out! I'll fix them soon - particularly useful is the open soruce licensing thing, I haven't really licensed anything before so will have a look.

**Comment by Daniel-CG-Wright** [comment]
#6 
#7 
#8 
#9

**Comment by Daniel-CG-Wright** [comment]
fixed with latest main commit, but the website image will not be updated until the extended spotify history branch is merged into main
